# Generated by Django 6.0.1 on 2026-01-14 11:34

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_body',
            field=tinymce.models.HTMLField(),
        ),
    ]
