# Generated by Django 6.0 on 2026-01-07 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_links', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallinks',
            options={'verbose_name_plural': 'Social Links'},
        ),
    ]
